import { useRouter } from 'next/router'

export default function Privacy() {
  const router = useRouter()
  const { id } = router.query
  return (
    <div>
      <h1>Privacy Policy</h1>

      <p>
        Athasha.IO respects your privacy, and if you provide us individual identifying information,
        we use that information only for the purpose of serving you better. &quot;Individual identifying
        information&quot; is information that enables us to identify you, such as your email address,
        name, title, and mailing address. Athasha.IO uses individual identifying information to
        personalize your experience on our website and also to be able to selectively send you
        communications (either electronically or otherwise) that may be of interest to you.
      </p>

      <h4>Notice and Disclosure</h4>

      <p>
        This online privacy statement is made available to you to let you know how Athasha.IO
        collects and uses information about visitors to Athasha.IO&apos;s websites. Athasha.IO collects
        information regarding visitors to our websites. Information collected includes,
        but is not limited to, the IP address and/or domain name from which you are accessing
        an Athasha.IO website, web pages accessed, and individual identifying information volunteered
        by you such as name, title, email and mailing addresses, and your preferred means of
        communication. Athasha.IO may make individual identifying information available to authorized
        representatives of Athasha.IO products. From time to time, Athasha.IO may make this information
        available to our partners. Athasha.IO also uses such information to contact people for product
        support and marketing purposes.
      </p>

      <h4>Changes to this Policy</h4>

      <p>
        Please note that this Privacy Policy may change from time to time. Athasha.IO will post any
        Policy changes on this page.
      </p>

      <h4>Use of Cookies</h4>

      <p>
        A &quot;cookie&quot; is a small data file that certain websites write to your hard drive when you visit them.
        A cookie file can contain information such as a user ID that the site uses to track the pages
        you&apos;ve visited, but the only personal information a cookie can contain is information you supply
        yourself. A cookie can&apos;t read data off your hard disk or read cookie files created by other sites.
        Some parts of the Athasha.IO websites use cookies to track user traffic patterns. We do this in order
        to determine the usefulness of Athasha.IO information to our users and to see how effective our navigational
        structure is in helping users reach that information. Athasha.IO does not share this information or sell it
        to any third party without your express consent. If you prefer not to receive cookies on Athasha.IO websites,
        you can set your browser to warn you before accepting cookies and refuse the cookie when your browser
        alerts you to its presence. You can also refuse all cookies by turning them off in your browser.
        Some areas of our websites may require the use of cookies, such as ordering products online and
        creating an Athasha.IO profile.
      </p>

      <h4>Google Analytics</h4>

      <p>
        Athasha.IO websites use Google Analytics, a web analytics service provided by Google, Inc. (&quot;Google&quot;).
        Google Analytics uses &quot;cookies,&quot; which are text files placed on your computer, to help websites analyze
        how users use the site. The information generated by the cookie about your use of a website (including your IP address)
        will be transmitted to and stored by Google on servers in the United States. Google will use this
        information for the purpose of evaluating your use of the website, compiling reports on website activity
        for website operators, and providing other services relating to website activity and Internet usage.
        Google may also transfer this information to third parties where required to do so by law, or where
        such third parties process the information on Google&apos;s behalf. Google will not associate your IP address
        with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings
        on your browser; however, please note that if you do this, you may not be able to use the full functionality
        of an Athasha.IO website. By using an Athasha.IO website, you consent to the processing of data about you by Google
        in the manner and for the purposes set out above.
      </p>
    </div>
  )
}
