//https://fonts.google.com/
import './Roboto-Black.ttf'
import './Roboto-BlackItalic.ttf'
import './Roboto-Bold.ttf'
import './Roboto-BoldItalic.ttf'
import './Roboto-Italic.ttf'
import './Roboto-Light.ttf'
import './Roboto-LightItalic.ttf'
import './Roboto-Medium.ttf'
import './Roboto-MediumItalic.ttf'
import './Roboto-Regular.ttf'
import './Roboto-Thin.ttf'
import './Roboto-ThinItalic.ttf'
import './LibreBarcode39-Regular.ttf'
import './LibreBarcode39Text-Regular.ttf'
import './LibreBarcode128Text-Regular.ttf'
import './LibreBarcode128-Regular.ttf'
