alias Terminal.App
alias Terminal.Tty
alias Terminal.Term
alias Terminal.Theme
alias Terminal.Canvas
alias Terminal.Runner
alias Terminal.Teletype
alias Terminal.Linux
alias Terminal.Code
alias Terminal.Demo
